---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "configs-{{ include "..name" . }}"
data:
  vault-agent-config.hcl: |
    exit_after_auth = true
    pid_file = "/home/vault/pidfile"

    auto_auth {
        method "kubernetes" {
            mount_path = "auth/kubernetes"
            config = {
                role = "postgrest"
            }
        }

        sink "file" {
            config = {
                path = "/home/vault/.vault-token"
            }
        }
    } 
  consul-template-config.hcl: {{ .Files.Get "files/consul-template.hcl" | trim | quote  }}
