---
resource_types:
  - name: helm
    type: docker-image
    source:
      repository: linkyard/concourse-helm-resource
  - name: kube-authenticator
    type: docker-image
    source:
      repository: 7imbrook/kube_authenticate

resources:
  - name: postgrest-deployment
    type: git
    icon: github-circle
    source:
      uri: "https://github.com/timbrook-life/postgrest-deployment"
      branch: master
  - name: auth
    type: kube-authenticator
    icon: lock-outline
    source:
      token: ((digital_ocean.token))
  - name: helm-push-local-chart
    type: helm

jobs:
  - name: Deploy Chart
    serial: true
    plan:
      - get: postgrest-deployment
        trigger: true
      - get: auth
      - put: helm-push-local-chart
        params:
          release: postgrest
          namespace: api
          kubeconfig_path: auth/config.yaml
          chart: ./postgrest-deployment/api-deployment
          values: ./postgrest-deployment/api-deployment/values.yaml
